### ISSUE TITLE
Trigger pipeline execution from CLI

### ISSUE THREAD

**Issue by nicktravis-8451** [harness/harness-cli#54]
We spoke about this idea with a few folks via during an onboarding call, but wanted to raise the issue here. It would be useful to have the ability to trigger a run of an pipeline from the harness CLI. I know it is very early days and much isn't implemented, and imagine that is somewhere in your plans. Is there a public roadmap or similar that we can see, and does this fit into your plan for the CLI in general - to provide access to most/all functions available via API calls?

**Comment by dewan-ahmed** [comment]
@nicholaslotz can we close this since https://github.com/harness/harness-cli/pull/69 is merged?
